# Generated by Django 5.0.7 on 2024-08-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_closingstock_order_product_unit_wastage_delete_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='previous_status',
        ),
    ]
