# Generated by Django 5.0.7 on 2024-08-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_order_previous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='previous_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
